New component: Button
Netcentric/edge-delivery-solari pull request #14
Opened 2024-01-30 16:30 UTC by adrielTosi

- New button and all styles for it
- Cleanup 
- Move `assets` folder to `src`
- New `icons` folder

Storybook doesn't do well with importing SVGs into a `.stories.ts` file. If you want to test icons, import the icons inside the Button component itself using 
```
import { ReactComponent as YourIcon } from '/assets/icons/...svg
```
And set iconLeft or iconRight as the imported svg component.

2024-01-30 16:49 UTC, nagarajnetcentric requested changes

2024-01-30 16:49 UTC, nagarajnetcentric commented on apps/frontend/src/App.scss
> +.btn-secondary {
`App.scss` is a global style sheet for now. So please move button styles to `button.css` or `Button.scss` file. You can create folder `components/Button` and move both files there.

2024-01-31 11:03 UTC, alexiscoelho approved these changes

2024-01-31 11:22 UTC, nagarajnetcentric approved these changes

2024-01-31 11:33 UTC, merged